# Generated by Django 5.1 on 2024-08-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('upc', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('title_english', models.CharField(max_length=200)),
                ('color_english', models.CharField(max_length=50)),
                ('size_english', models.CharField(max_length=20)),
                ('images_link', models.URLField()),
                ('english_description', models.TextField()),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_weight_unit', models.CharField(max_length=10)),
                ('case_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('case_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('case_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('case_unit', models.CharField(max_length=10)),
                ('pieces_per_case', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dandd_app.category')),
            ],
        ),
    ]
